### PR TITLE
254 professor add grades

### LINKED ISSUE #254: As a professor, I want to be able to add grades for my students
Test: log in as prof, select a section, change a grade, submit, use back button

### PR DESCRIPTION
**Pull request by oceancypress**
add professors ability to add and change grades for students in their sections. 
Test: log in as prof, select a section, change a grade, submit, use back button

Closes #254

### CODE REVIEW

**Comment by bjmckenz** [comment]
What's the "if POST then GET" (line37) for?

**Comment by oceancypress** [comment]
> What's the "if POST then GET" (line37) for?

You mean line 41? It checks to make sure it has the right student? (maybe I assumed wrong about how the forms send back data, are you implying I dont need the if?) @bjmckenz

**Review by jeffreicher — COMMENTED** [review]
code review looks good

**Review by jeffreicher — APPROVED** [review]
pulled in branch and it works as intended

**Comment by oceancypress** [comment]
merging since no response and approved by Jeff

**Pull request merged**
